import React, { useState } from 'react';
import UploadForm from './components/UploadForm';
import Emoji from './components/Emoji';
import './App.css';

// Moved translations outside to prevent re-creation on every render
const translations = {
  en: {
    title: 'Waste Material Art Generator',
    description: 'Turn waste into wonderful DIY creations',
    category: 'Category:',
    confidence: 'Confidence:',
    reset: 'Reset',
    resetting: 'Resetting...',
    print: '🖨️ Print / Save as PDF',
    analyzing: 'AI is analyzing your image...',
    aiSuggestions: 'AI Suggested Ideas:',
    noIdeas: 'No ideas found. Try another image!',
    uploadPrompt: 'Upload an image to generate AI ideas...',
    printTitle: 'My DIY Art Project'
  },
  ta: {
    title: 'வெஸ்ட் மாடீரியல் கலை உருவாக்கி',
    description: 'குப்பைகளை அழகான DIY படைப்புகளாக மாற்றுங்கள்',
    category: 'வகை:',
    confidence: 'உறுதி:',
    reset: 'புதுப்பிக்கவும்',
    resetting: 'புதுப்பிக்கப்படுவது...',
    print: '🖨️ பிரிண்ட் / PDF சேமி',
    analyzing: 'AI உங்கள் படத்தை ஆய்வு செய்கிறது...',
    aiSuggestions: 'AI பரிந்துரைத்த யோசனைகள்:',
    noIdeas: 'யோசனைகள் எதுவும் காணப்படவில்லை.',
    uploadPrompt: 'AI யோசனைகளை உருவாக்க ஒரு படத்தை பதிவேற்றுங்கள்...',
    printTitle: 'எனது DIY கலைத் திட்டம்'
  },
  si: {
    title: 'අපද්‍රව්‍ය කලා නිර්මාණකරු',
    description: 'අපද්‍රව්‍යය විශ්මයජනක DIY නිර්මාණවලට පරිවර්තනය කරන්න',
    category: 'ප්‍රවර්ගය:',
    confidence: 'ආශ්වාසය:',
    reset: 'පෙරළිය',
    resetting: 'පෙරළීම...',
    print: '🖨️ මුද්‍රණය / PDF ලෙස.',
    analyzing: 'AI ඔබේ රූපය විශ්ලේෂණය කරයි...',
    aiSuggestions: 'AI විසින් යෝජනා කරන ලද අදහස්:',
    noIdeas: 'අදහස් කිසිවක් හමු නොවීය.',
    uploadPrompt: 'AI අදහස් ජනනය කිරීමට රූපයක් උඩුගත කරන්න...',
    printTitle: 'මගේ DIY කලා ව්‍යාපෘතිය'
  }
};

const App = () => {
  const [predictionInfo, setPredictionInfo] = useState(null);
  const [loading, setLoading] = useState(false);
  const [language, setLanguage] = useState('en');
  const [formKey, setFormKey] = useState(Date.now());

  const t = translations[language]; // Shortcut for current language

  const handlePredict = (data) => {
    // Handle both Axios response objects and direct data objects
    const result = data.data ? data.data : data;
    setPredictionInfo(result);
    setLoading(false);
  };

  const handleReset = () => {
    setLoading(true);
    setPredictionInfo(null);
    setFormKey(Date.now()); // Forces UploadForm to re-mount/reset
    setTimeout(() => setLoading(false), 800);
  };

  const handlePrint = () => {
    const printContent = document.getElementById('printArea').innerHTML;
    const win = window.open('', '_blank', 'width=900,height=700');
    
    win.document.write(`
      <html>
        <head>
          <title>${t.printTitle}</title>
          <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #2c3e50; line-height: 1.6; }
            .print-header { text-align: center; border-bottom: 2px solid #3498db; margin-bottom: 20px; padding-bottom: 10px; }
            .prediction-box { border: 2px solid #3498db; padding: 15px; border-radius: 10px; margin-bottom: 20px; background: #f0f7ff; }
            .tag { background: #3498db; color: white; padding: 4px 10px; border-radius: 15px; font-size: 0.8em; font-weight: bold; }
            .idea { margin-top: 20px; padding: 15px; background: #f9f9f9; border-left: 5px solid #2ecc71; border-radius: 8px; page-break-inside: avoid; }
            .idea h4 { color: #27ae60; margin: 0 0 5px 0; }
            .prep-list { font-size: 0.9em; color: #666; font-style: italic; margin-top: 10px; }
            .footer { margin-top: 30px; text-align: center; font-size: 0.8em; color: #aaa; }
          </style>
        </head>
        <body>
          <div class="print-header">
            <h1>${t.printTitle}</h1>
            <p>${t.description}</p>
          </div>
          ${printContent}
          <div class="footer">Generated by Waste Material Art AI</div>
        </body>
      </html>
    `);
    win.document.close();
    win.print();
  };

  return (
    <div className="App">
      {loading && (
        <div className="loading-overlay">
          <div className="loader-box">
            <div className="spinner"></div>
            <p>{t.analyzing}</p>
          </div>
        </div>
      )}

      <div className="language-selector">
        <select value={language} onChange={(e) => setLanguage(e.target.value)} className="language-select">
          <option value="en">English</option>
          <option value="ta">தமிழ்</option>
          <option value="si">සිංහල</option>
        </select>
      </div>

      <header className="app-header">
        <h1 className="title">
          <Emoji symbol="♻️" label="recycle" /> {t.title}
        </h1>
        <p className="description">{t.description}</p>
      </header>

      <div className="main-container">
        {/* Upload Section */}
        <div className="card">
          <UploadForm 
            key={formKey} 
            onPredict={handlePredict} 
            language={language} 
            setLoading={setLoading} 
          />
          <button onClick={handleReset} className="btn-action reset-button">
            {loading ? t.resetting : <><Emoji symbol="🧹" label="broom" /> {t.reset}</>}
          </button>
        </div>

        {/* Results Section */}
        <div className="card">
          {predictionInfo ? (
            <div id="printArea">
              <h3 className="result-header">🔍 Prediction Result</h3>
              <div className="prediction-box">
                <p>
                  <strong className="label-text">{t.category} {predictionInfo.label || 'Unknown'}</strong>
                </p>
                <span className="tag">
                  {t.confidence} {predictionInfo.confidence || '0'}%
                </span>
              </div>
              
              <div className="diy-suggestions-container">
                <h4 className="suggestions-title">{t.aiSuggestions}</h4>
                {predictionInfo.diy_ideas && predictionInfo.diy_ideas.length > 0 ? (
                  predictionInfo.diy_ideas.map((idea, index) => (
                    <div key={index} className="idea">
                      <h4>{idea.title}</h4>
                      <p>{idea.description}</p>
                      <div className="prep-list">
                        <strong>Materials:</strong> {idea.preparations?.join(', ') || 'Not specified'}
                      </div>
                    </div>
                  ))
                ) : (
                  <p className="no-ideas-text">{t.noIdeas}</p>
                )}
              </div>
            </div>
          ) : (
            <div className="empty-state">
              <img src="preview.png" alt="Preview" className="preview-img" />
              <p>{t.uploadPrompt}</p>
            </div>
          )}

          {predictionInfo && (
            <button onClick={handlePrint} className="btn-action print-button">
              {t.print}
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

export default App;
